
server:
  port: 8000
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-member:
      path: /api-member/**
      serviceId: member
    api-order:
      path: /api-order/**
      serviceId: order
      